version: 2.1

jobs:
  python-job:
    docker:
      - image: circleci/python:3.10.1-node-browsers

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            cd python-homework
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            cd python-homework
            pytest --template=html1/index.html --report=report.html

      - store_artifacts:
          path: python-homework/report.html
          destination: python-report

workflows:
  build-and-test:
    jobs:
      - python-job