version: 2.1

jobs:

  python-tests:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: |
            cd python-homework
            pip install -r requirements.txt

      - run:
          name: Run Python tests
          command: |
            cd python-homework
            pytest


  cypress-tests:
    docker:
      - image: cypress/browsers:node-18.12.0-chrome-107

    steps:
      - checkout

      - run:
          name: Install Cypress dependencies
          command: |
            cd cypress-homework
            npm install

      - run:
          name: Run Cypress tests
          command: |
            cd cypress-homework
            npx cypress run


  postman-tests:
    docker:
      - image: postman/newman:alpine

    steps:
      - checkout

      - run:
          name: Run Postman collection
          command: |
            newman run "ClickUp API.postman_collection.json" \
            -e "ClickUp Main.postman_environment.json"


workflows:
  build-and-test:
    jobs:
      - python-tests
      - cypress-tests
      - postman-tests